name: Java CI with Maven

on: 
  push:
    branches: ["master", "tijani"]
  pull_request:
    branches: ["main"]

jobs:


  build:
    name: Build without test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify 
        run: mvn -B clean verify
